name: jndi-example-liferay-workspace
services:

  liferay-workspace:
    build: ./liferay-workspace
    image: jndi-example-liferay-workspace/liferay-workspace
    container_name: liferay-workspace
    tty: true
    ports:
      - "8080:8080" # http
      - "8000:8000" # debug
      - "11311:11311" # osgi console
      - "9010:9010" # jmx
    networks:
      - jndi-example-liferay-workspace

  db:
    image: postgres:15.8
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "muchsecureverywow"
    networks:
      - jndi-example-liferay-workspace

volumes:
  db-data:

networks:
  jndi-example-liferay-workspace:
    driver: bridge